# Generated by Django 5.2.7 on 2025-10-20 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="price_range",
            field=models.CharField(
                choices=[
                    ("$", "Budget"),
                    ("$$", "Moderate"),
                    ("$$$", "Expensive"),
                    ("$$$$", "Very Expensive"),
                ],
                default="₵₵",
                max_length=5,
            ),
        ),
    ]
